### ISSUE TITLE
Some glitches with MID building

### ISSUE THREAD

**Issue by Zkir** [vvoovv/blender-geo#201]
![image](https://user-images.githubusercontent.com/874906/86974515-2987e280-c17f-11ea-9d15-f766bcf0ae04.png)

There are the following poblems:
1.  Spire is not generated
2. Levels are strange. min_level tag is ignored? (compare with [OSMBuildings](https://osmbuildings.org/?lat=55.74725&lon=37.58613&zoom=18.0&tilt=45&rotation=48) )
3. building:colour is ignored (the building should be sandy gray)

[MID_building.zip](https://github.com/vvoovv/blender-osm/files/4893473/MID_building.zip)

**Comment by vvoovv** [comment]
> 3. building:colour is ignored (the building should be sandy gray)

See https://github.com/vvoovv/pml/issues/14

**Comment by vvoovv** [comment]
> 1. Spire is not generated

Fixed!

**Comment by vvoovv** [comment]
> 3. building:colour is ignored (the building should be sandy gray)

Fixed!

**Comment by Zkir** [comment]
Tested with the following results:
1. Spire -- OK. 
2. Levels -- still wrong (FAIL)
3. Building colour  - OK.

Additional problem found: 
building:material behaves strangely. 
for **building:material=wood** textures are still random.

**Comment by vvoovv** [comment]
No wood textures are available.

**Comment by Zkir** [comment]
OK, how to submit textures? ;)

**Comment by Zkir** [comment]
Tested 30.07.2020 -- the same results: 
* textures for higher levels are strangely condensed (FAIL)
